### ISSUE TITLE
feat: Implementation of Authentication using NextAuth

### ISSUE THREAD

**Issue by soorya-u** [soorya-u/Grade-Grove#18]
# Implementation of Authentication using NextAuth

## TODO

- [x] Implementation of Login Form
- [x] Implementation of SignUp Form
- [x] Auth using Database
- [x] Github, Google OAuth
- [x] Role based Auth

**Comment by soorya-u** [comment]
Upgrade to NextAuth v5
