### ISSUE TITLE
feat: Add React Email and Resend to the Project for Email Verification

### ISSUE THREAD

**Issue by soorya-u** [soorya-u/Grade-Grove#27]
# Add React Email and Resend to the Project for Email Verification

## TODO

- [x] Add Domain to Resend
- [ ] Design a React Mail
- [ ] Integration with NextAuth
